"""empty message

Revision ID: 76f78e7c57ec
Revises: 
Create Date: 2017-05-29 00:25:36.768014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f78e7c57ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('unidade_medida', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('qtd_minima', sa.Integer(), nullable=True),
    sa.Column('item_estoque_vld', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_produto'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('compra',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_compra')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compra')
    op.drop_table('produto')
    # ### end Alembic commands ###
