"""empty message

Revision ID: 979f09a03bee
Revises: 76f78e7c57ec
Create Date: 2017-06-01 10:53:57.549677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979f09a03bee'
down_revision = '76f78e7c57ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidademedida',
    sa.Column('id_unidade_medida', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_unidade_medida'),
    sa.UniqueConstraint('nome')
    )
    op.add_column('produto', sa.Column('id_unidade_medida', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produto', 'unidademedida', ['id_unidade_medida'], ['id_unidade_medida'])
    op.drop_column('produto', 'unidade_medida')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('unidade_medida', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'id_unidade_medida')
    op.drop_table('unidademedida')
    # ### end Alembic commands ###
